# .travis.yml with conda modeled along https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update

install:
  # miniconda download and setup
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Build conda environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda env update -n test-environment -f environment-2.7.yml
    else
      conda env update -n test-environment -f environment-3.5.yml
    fi
  - source activate test-environment
  - python setup.py install

script:
  - nosetests ozelot.tests

