from setuptools import setup

setup(name='ozelot',
      version='0.2',
      description='An open source ETL stack',
      classifiers=[
          'Development Status :: 2 - Pre-Alpha',
          'License :: OSI Approved :: MIT License',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3.5',
          'Topic :: Scientific/Engineering :: Information Analysis',
      ],
      keywords='data analytics ETL',
      url='http://github.com/trycs/ozelot',
      author='Eberhard Hansis',
      license='MIT',
      packages=['ozelot',
                'ozelot.orm',
                'ozelot.etl'],
      install_requires=[
          'pandas>=0.17.0',
          'sqlalchemy>=1.0.0',
          'luigi>=2.2.0',
          'keyring',
          'requests',
          'sadisplay',
          'future',
      ],
      test_suite='nose.collector',
      tests_require=['nose',
                     'coverage',
                     'lxml'],
      include_package_data=True,
      zip_safe=False)
