name: travis-environment-2.7
dependencies:
  - python=2.7
  - numpy
  - pandas
  - lxml
  - scipy
  - matplotlib
  - pip:
    - sqlalchemy
    - luigi
    - keyring
    - pygeoj
    - jinja2
    - openpyxl
    - argparse
    - requests
    - xlrd
    - seaborn
    - sadisplay
    - future
