name: ozelot-eurominder-2.7
dependencies:
  - python=2.7
  - numpy
  - pandas
  - scipy
  - matplotlib
  - graphviz
  - pip:
    - git+https://github.com/trycs/ozelot.git
    - pygeoj
    - requests
    - jinja2
    - openpyxl
