name: ozelot-superheroes-3.5
dependencies:
  - python=3.5
  - numpy
  - pandas
  - lxml>=2.9.4
  - scipy
  - matplotlib
  - graphviz
  - pip:
    - ozelot
    - argparse
    - requests
    - xlrd
    - seaborn
    - jinja2
    - openpyxl
